name: CI/CD Pipeline
on:
 push:
 branches:
 - main # Trigger workflow on push to the main branch
jobs:
 build:
 runs-on: ubuntu-latest
 # Use an Ubuntu environment for the job
 steps:
 - name: Checkout code
 uses: actions/checkout@v3
 # Checkout the code from the repository
 - name: Set up Java
 uses: actions/setup-java@v3
 with:
 distribution: 'temurin'
 # Use the Temurin distribution of Java
 java-version: '11'
 # Set Java version to 11
 - name: Build with Maven
 run: mvn -B package --file pom.xml
 # Build the project using Maven
 - name: Run tests
 run: mvn test # Run unit tests using Maven
 deploy:
 needs: build
 # Run deploy job only if the build job succeeds
 runs-on: ubuntu-latest
 steps:
 - name: Deploy to Staging
 run: echo "Deploying to staging environment..."
 # Placeholder for actual deployment
